### ISSUE TITLE
[Geolocalization] - Improvement and new Features

### ISSUE THREAD

**Issue by ValerioVillani** [publicv-org/publicv#299]
**RoadMap geolocalization:**

We realized that in order to help recruiters to find the best candidate possible, the geolocalization features could play a crucial role.
Therefore we're going to make some crucial improvements to make our geolocalization system efficient and effective.

**The following is the roadmap to start this new feature:**

- [ ] Willing to relocate. the user that checks the "willing to relocate" box is presented with UX to insert cities in which he is willing to relocate. Each city will be geocoded and associated with its Cv. Each user will then have a main location and n "relocations".
- [ ] Search Bar improvement. The search bar will have 2 forms instead of 1. The first one is "skill" the second one is "location" (or modality, for instance, "remote").
- [ ] Map view - Results. On the map, for each Cv, we only show the nearest result relative to the centre of the search.
- [ ] Map view - Dynamic zoom. Once the users perform research by location (For example "Neaples"), it would be nice to have a dynamic zoom on that location.
- [ ] Main Location and Relocation. the recruiter watching the results should see which people are willing to relocate in order to distinguish the main location for "relocations".

Once we perform a good geolocalization the further step will be the following

**Since that we want to provide the most efficient product possible both for recruiters and candidates, there are a few more features we need to add. One of those is the "Preferences section".**

We have to follow the following steps:

- [ ]  Your Preferences

Your Preferences has to show 4 boxes:

- [ ]  Type of contract (Temp/perm/part/freelance)
- [ ]  Salary expectation
- [ ]  Notice period
- [ ]  Ready to relocate

**Once we have all editable boxes we have to:**

Show them in profile preview [Candidate Search] - Improve profile's preview to make the research more efficient #297

- [ ] Make them (Salary, Notice, Type of contact, ready to relocate) searchable fields
