### ISSUE TITLE
CV Format - Improvement and new features

### ISSUE THREAD

**Issue by ValerioVillani** [publicv-org/publicv#309]
CV Format is one of YouCV key Features. 
As a job seeker I want to know that the CV I'm doing on YouCV is the best possible. 

In order to make this feature the best possible we need to do some Improvement and the following is the roadmap to follow:

- [ ] Make YouCV Published By Default
- #106 
- #267 
- #294 
- #293 
- [ ] Add "preferences Section"
- [ ] Video Guides Tools
